### ISSUE TITLE
Generate random instance of any class

### ISSUE THREAD

**Issue by serpro69** [serpro69/kotlin-faker#1]
Thinking if something like this: https://blog.kotlin-academy.com/creating-a-random-instance-of-any-class-in-kotlin-b6168655b64a would be useful to have here (And whether it fits into this library?)

**Comment by samneirinck** [comment]
Is it no longer planned to be implemented? Been looking for a while for a library which provides the functionality to generate instances of a random (data) class.

**Comment by serpro69** [comment]
Hi, it's actually implemented. I think I've forgotten to update the issue with the details and just closed it.
See here https://github.com/serpro69/kotlin-faker#generating-a-random-instance-of-any-class for details on usage.

**Comment by samneirinck** [comment]
Epic, thanks!
