### ISSUE TITLE
Calling `internet.freeEmail()` returns domain instead of an email address

### ISSUE THREAD

**Issue by jershell** [serpro69/kotlin-faker#12]
How to get an email address?

In original, I could
```ruby
Faker::Internet.email #=> "kirsten.greenholt@corkeryfisher.info"
```

**Comment by serpro69** [comment]
This is added to version 1.0.
See usage here: https://github.com/serpro69/kotlin-faker/blob/master/doc/internet.md

**Comment by jershell** [comment]
it's great. Thank you very much!
