### ISSUE TITLE
Use ' in fake names

### ISSUE THREAD

**Issue by VyacheslavHalpukov** [serpro69/kotlin-faker#147]
A name is generated with ` for example: O'Hara
When you insert this generated name into ' ', you get an error:

' O'Hara '

 I couldn't find a way to turn off generation of such information

**Comment by serpro69** [comment]
Hi @VyacheslavHalpukov ,

Do I understand correctly that you want to replace single quote in a name with a backtick? Why not do this with replace function? 
```
name.replace("'", "`")
```

**Comment by VyacheslavHalpukov** [comment]
> Hi @VyacheslavHalpukov ,
> 
> Do I understand correctly that you want to replace single quote in a name with a backtick? Why not do this with replace function?
> 
> ```
> name.replace("'", "`")
> ```

Not elegant i found same way. I expected something from inside methods which resolve this problem.

**Comment by serpro69** [comment]
The general rule is values are returned as they are defined in the .yml files.
I really don't think it makes sense to do something like this for every single method. And the alternative is doing this selectively, but then based on what criteria? And this is not even considering your very narrow use-case.
So hence, I like to keep things as simple as possible and not modify the return values which are defined in the .yml files unless it really makes sense to do so.
