### ISSUE TITLE
StarWars quotes not working

### ISSUE THREAD

**Issue by TZanke** [serpro69/kotlin-faker#148]
https://github.com/serpro69/kotlin-faker/blob/e49385d3240a8e0051c28d764d5723e6dbcef10f/core/src/main/kotlin/io/github/serpro69/kfaker/provider/StarWars.kt#L30

looks like oldValue and newValue are replaced.
`.starWars.quotes("admiral_ackbar")` isn't working as described. 

The key uses underscore: 
https://github.com/serpro69/kotlin-faker/blob/abe4eaa4aa1673707719332566cb52ea746672dc/core/src/main/resources/locales/en/star_wars.yml#L226

**Comment by serpro69** [comment]
Hi @TZanke ,
Yes, looks like you're right. Probably a typo, old and new value in `replace` should've been reversed. 
Would you like to submit a PR with a fix also or do you want me to fix this?
