### ISSUE TITLE
JPMS: Wrong export in module-info

### ISSUE THREAD

**Issue by overfullstack** [serpro69/kotlin-faker#149]
I am using JPMS and unable to import `faker` classes and they are not exported. Instead I see wrong exports in the decompiled class. PFA the screenshot

```
module com.fasterxml.jackson.annotation {
    exports com.fasterxml.jackson.annotation;

    opens com.fasterxml.jackson.annotation;
}
```

<img width="1904" alt="Screenshot 2022-08-01 at 10 48 23" src="https://user-images.githubusercontent.com/13434911/182077591-44b939c9-f0dc-407e-8501-8d368ae51f0e.png">

**Comment by serpro69** [comment]
Hi @overfullstack , thanks for reporting this.

I don't think I've ever explicitly added modules support to faker - a lot of the code I work with is still stuck on java 8... :D But this looks very weird nevertheless, not sure why the module would be registered with this name...
I'll take a closer look at it as soon as I have some time, but also feel free to submit a PR with a fix if you want to.

**Comment by overfullstack** [comment]
@serpro69 thanks, even I couldn't locate where this is coming from, or I would have raised a PR instead of issue :)

**Comment by serpro69** [comment]
I suspect that the module-info.class comes from a shadowed jackson dependency and is added automatically by shadow plugin.
The way I see going about this issue is we need to add a module-info.class manually for JPMS support in kotlin-faker, and also probably add explicit support for java9 (via own jar that would include this module-info.class?)
I'll need to experiment a bit with this.

**Comment by serpro69** [comment]
I have excluded the incorrect module-info.class from the jar.
Can you test the `1.12.0.-rc.2` version from this repo: `https://oss.sonatype.org/content/repositories/iogithubserpro69-1056` and see if that fixes the issue you're facing.

Note that this only fixes inclusion of incorrect module-info.class in the jar. I haven't added any explicit support for JPMS as this requires a move to java9+ as primary target. I don't have much experience with java modules yet and I also don't see how modules make anything better really. But I can definitely see the need for moving to java9+ as soon as possible, so if this is something you want to see in the future - please open a separate issue for this.

**Comment by overfullstack** [comment]
Thanks @serpro69 this resolved my issue!
