### ISSUE TITLE
Application crash. Regex syntax error

### ISSUE THREAD

**Issue by Gizmodo** [serpro69/kotlin-faker#151]
**v1.12.0-rc.0**
Use simple init:
```
val config = fakerConfig { locale = "en" }
val faker = Faker(config)
```
Get error:
 Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 26
    #\{(?!\d)(\p{L}+\.)?(.*?)}

If I use v1.11.0 - no exception occurs

**Comment by serpro69** [comment]
Hi @Gizmodo , thanks for reporting this.
Weird that it's not caught by integration tests. 
I'll try to reproduce this. What version of kotlin/java are you using?

**Comment by serpro69** [comment]
I can see that a backslash was removed from the regex in https://github.com/serpro69/kotlin-faker/commit/e17c38f296a2a2e720220d98339e3bd444cc1761 :
```diff
- @Suppress("RegExpRedundantEscape")
- private val curlyBraceRegex = Regex("""#\{(?!\d)(\p{L}+\.)?(.*?)\}""")
+ private val curlyBraceRegex = Regex("""#\{(?!\d)(\p{L}+\.)?(.*?)}""")
```

And it also corresponds to the index, so might be causing this issue.

But I can't reproduce this locally so far, so might be some kotlin/java version incompatibility?

I will restore the backslash first and then maybe you could test and see if that fixes it @Gizmodo ?

**Comment by Gizmodo** [comment]
> 
Kotlin 1.7.10

**Comment by Gizmodo** [comment]
@serpro69 Fix works. Issue may be closed.

**Comment by serpro69** [comment]
version `1.12.0-rc.2` is released to central and should soon be available.
