### ISSUE TITLE
Remove SLF4J

### ISSUE THREAD

**Issue by ansman** [serpro69/kotlin-faker#189]
This library currently depends on SLF4J but does not actually use it. This can cause some warnings to be logged when other libraries that have optional support for SL4J tries to use it but unless set up this will log a warning.

**Comment by serpro69** [comment]
Hi @ansman ,

Yeah, I think this makes sense. IIRC I've used slf4j intermittently for some debugging way back, and it probably creeped into one of the commits.

Do you want to make a PR for this?
