### ISSUE TITLE
Postal Code for CA/UK returns regex, not an actual Postal Code

### ISSUE THREAD

**Issue by efenderbosch-atg** [serpro69/kotlin-faker#192]
Probably for any other Locale that allows characters in their postal codes as well, but I haven't checked.

```kotlin
val EN_CA_FAKER = faker {
    fakerConfig { locale = "${Locale.ENGLISH.language}-${Locale.CANADA.country}" }
}

println(EN_CA_FAKER.address.postalCode()
```

Will print `/[A-CEGHJ-NPR-TVXY][0-9][A-CEJ-NPR-TV-Z] ?[0-9][A-CEJ-NPR-TV-Z][0-9]/`

This will print a CA postal code as expected:

```println(EN_CA_FAKER.string.regexify(EN_CA_FAKER.address.postcode()).replace("/", ""))```

I think the issue is in `Address.kt` @ line 39:
```kotlin
    fun postcode() = with(fakerService) {
        when (faker.config.locale) {
            "nl" -> resolve("postcode").generexify().replace("/", "")
            else -> resolve("postcode").numerify()
        }
    }
```

That should be:
```kotlin
    fun postcode() = with(fakerService) {
        when (faker.config.locale) {
            "nl" -> resolve("postcode").generexify().replace("/", "")
            else -> resolve("postcode").regexify().replace("/", "")
        }
    }
```

edit: It looks like the code in `master` should fix this for the `en-GB` Locale, but not for `en-CA`:
```kotlin
    fun postcode() = with(fakerService) {
        when (faker.config.locale) {
            "nl", "en-GB" -> resolve("postcode").generexify().replace("/", "")
            else -> resolve("postcode").numerify()
        }
    }
```

**Comment by serpro69** [comment]
Hi @efenderbosch-atg , 
Thanks for opening this issue!

Yes, you're likely right that en-GB locale needs to be handled separately, like the `nl` one.
Would you like to submit a PR with a fix?

**Comment by efenderbosch-atg** [comment]
I can probably do that. I'm wondering if the `when` is required at all? Would this simply cover all use cases?

`fun postcode() = with(fakerService) { resolve("postcode").generexify().replace("/", "") }`

**Comment by serpro69** [comment]
> I can probably do that. I'm wondering if the `when` is required at all? Would this simply cover all use cases?
> 
> `fun postcode() = with(fakerService) { resolve("postcode").generexify().replace("/", "") }`

Up to you , but if you want to contribute - you're welcome to do so :)

No, it won't. Most postcodes aren't in the form of regex, but use `#` chars as a placeholder for a digit (e.g. https://github.com/serpro69/kotlin-faker/blob/3bb1657c80e0eb2415b57392fd6e2fa9845facae/core/src/main/resources/locales/en/address.yml#L511 ), which is what `else` handles.
Also I assume that generating strings from regexes is probably (haven't really tested it) slower than just returning a string and replacing `#` with a random digit.

**Comment by efenderbosch-atg** [comment]
PR #193 opened. This should cover all locales that don't use "#" based postal codes. Tests and Integration tests pass. Added a new test for en-CA postal codes.

**Comment by serpro69** [comment]
This should be available in latest snapshot after the build finishes.
Otherwise I'll make a new RC version later this week.
Thanks for your contribution
