### ISSUE TITLE
Regexify generates invalid value

### ISSUE THREAD

**Issue by axelfontaine** [serpro69/kotlin-faker#207]
Regex: `^[a-zA-Z\d](?:[a-zA-Z\d]|-(?!-)){0,38}$`

Example generated invalid value: `^2]?:0]-?!-?:A]$`

**Comment by serpro69** [comment]
This could also be an issue in the dependency, not in faker. Similar to #209 .

I'll take a look and see if I can reproduce it and will think if there's a possibility to fix.
But feel free to make a PR if you have some ideas on how this could be fixed ;)

**Comment by axelfontaine** [comment]
Another example:

Regex: `^AKIA\S{16}$`
Generated invalid value: `^AKIA蘕篝爈ᇦ$`
