### ISSUE TITLE
Regexify fails with StackOverflowError

### ISSUE THREAD

**Issue by axelfontaine** [serpro69/kotlin-faker#209]
Regex: `^arn:.+:.+:.*:([0-9]{12}):(.+)$`

**Comment by serpro69** [comment]
Thanks for opening the issue @axelfontaine ,

Let me check, I think it could be an issue in the `generex` dependency, since there's not much logic in faker itself regarding regexifying strings.

**Comment by axelfontaine** [comment]
@serpro69 It is most certainly downstream. However this could potentially mean that `generex` may have to be switched out for either an internal solution or another lib.

The answers to this question mention a few alternatives: https://stackoverflow.com/questions/22115/using-regex-to-generate-strings-rather-than-match-them

**Comment by axelfontaine** [comment]
Probably caused by https://github.com/mifmif/Generex/issues/56

**Comment by serpro69** [comment]
Good find :+1: and an old issue that didn't get much attention...
Well, this means generex will have to go :)
