### ISSUE TITLE
Suggestion: Add a Database Provider

### ISSUE THREAD

**Issue by mboisnard** [serpro69/kotlin-faker#221]
Be able to generate database entries just like the faker js version:

* collation, column, engine, type (from definition)
* mongodbObjectId (from hexadecimal generated string)

Sources:
* https://fakerjs.dev/api/database.html
* https://github.com/faker-js/faker/blob/next/src/modules/database/index.ts

**Comment by serpro69** [comment]
Hi @mboisnard ,

Thank you for the suggestion.
This is something that's been on the back of my head for awhile now :) Along with generating generating csv, json, ...

If you like to work on this - please let me know. Else I'll try to prioritize this myself in the near future to make it available for the next release.

**Comment by mboisnard** [comment]
Hello @serpro69 , thanks for your answer.

Yes actually I was talking about the same behavior as faker-js and I completely agree with you that the current implementation is generic and can be improved to match the possible data for each database.

I will take a look at your documentation, and try to contribute to the project :)

**Comment by serpro69** [comment]
Contributions are always welcome :) Thanks!

I think this https://github.com/serpro69/kotlin-faker/blob/master/CONTRIBUTING.adoc#adding-new-functionality should help with the implementation of this issue. But also feel free to ask if you need any help.

As I mentioned, the bigger part of the task here would be to gather the data itself. After that you should be able to follow the above documentation to add a new data provider implementation; but if something is unclear there - please let me know. I'd like to improve the contributing guidelines also if they're not good enough.

**Comment by mboisnard** [comment]
Thx for your suggestions, I created a branch to implement the databases behavior and I have several questions for you :)

For the MongoDB provider I would like to create a `generateObjectId` method based on a random date and inspired by the logic I found in JS here (https://steveridout.com/mongo-object-time/)

- MongoDB Provider is not based on a yaml file, so I would like to implement the `AbstractFakeDataProvider` class just like the StringProvider for example in the `databases` gradle module I just created. The  `AbstractFakeDataProvider`  class is marked as `internal`, is it intentional or have you not yet had the need?

- To be able to generate an objectId I would like to add a new method in the `RandomService` to generate an `OffsetDateTime` that can be used by anyone and by the MongoDB Provider. Can we access to the RandomService from a provider? (just removed the `internal` protection in `FakerService` for this field to make it work on my branch)

**Comment by serpro69** [comment]
Hey @mboisnard ,

Let me give you some existing code examples to make things easier to understand.

- Creating a new data provider that is not yaml-based outside of "core faker" is not supported. I'm not sure it makes much sense either to expose those things. Seems like a very specific use-case.
  - What I could suggest instead is having one `DatabaseProvider` implementation, which contains both common functionality, as well as specifics for the various `<DatabaseType>Provider`s accessible via additional property (take a look at https://github.com/serpro69/kotlin-faker/blob/5106afe80cf16d43b0370e5cc3558a91d0850029/faker/edu/src/main/kotlin/io/github/serpro69/kfaker/edu/provider/Educator.kt#L23 for example)

- To get access to `RandomService` from a data provider implementation, you can use this as an example:
  - First add it as a constructor parameter - https://github.com/serpro69/kotlin-faker/blob/5106afe80cf16d43b0370e5cc3558a91d0850029/faker/books/src/main/kotlin/io/github/serpro69/kfaker/books/provider/Dune.kt#L15-L18 
  - Then in the faker, you can use the `randomService` property that is available from the `AbstractFaker` - https://github.com/serpro69/kotlin-faker/blob/5106afe80cf16d43b0370e5cc3558a91d0850029/faker/books/src/main/kotlin/io/github/serpro69/kfaker/books/BooksFaker.kt#L39

**Comment by serpro69** [comment]
Don't know if the above made much sense :grin: Feel free to ask if you want me to clarify something further :)
