### ISSUE TITLE
Random Profile Picture

### ISSUE THREAD

**Issue by vanniktech** [serpro69/kotlin-faker#251]
Would be nice if the `Person` in addition to the `birthDate` also has a way to obtain a profile picture ideally also with male/female/neutral just like we can do when generating names.

**Comment by serpro69** [comment]
Hi @vanniktech ,
Thanks for the suggestion, sounds like a valid use-case, but would like some more details.
- Do you want to return a  file, a link to a file, or something else?
- Are you thinking of an array of pics for each type, or just one picture per type?
  - If we want an array of pictures, do you have any suggestions on where to source the data from? This likely needs to be some open third-party source with fake profile pics or something similar.

**Comment by vanniktech** [comment]
With consideration of https://github.com/serpro69/kotlin-faker/issues/226 the best might to just to get a `ByteArray` of an image with 32bit RGBA values?

Ideally, different pictures. Regarding the source, I don't have one in mind.

**Comment by serpro69** [comment]
> With consideration of #226 the best might to just to get a `ByteArray` of an image with 32bit RGBA values?

Good point.

I also don't know where one would be able to get pics that can be used for this, considering all sorts of things like privacy etc on top of it.
But I'll try to research a bit.
Feel free to update with more details if you come up with something.

**Comment by vanniktech** [comment]
https://uifaces.co/ this is as close as I've gotten when I took some time today to find some pictures.

**Comment by serpro69** [comment]
Good find, @vanniktech , thanks!
I've downloaded all the avatars and pushed them to a separate repo for now - https://github.com/serpro69/uifaces-ai-avatars
I'm not sure yet if I want to fetch and read avatars from remote location, or include as part of the jar. With the latter, I'd probably use a separate module, so that the size of the `core` module jar isn't needlessly increased.

Would you like to submit a PR for this? Otherwise I can take a look at implementing it myself.

**Comment by vanniktech** [comment]
> Would you like to submit a PR for this? Otherwise I can take a look at implementing it myself.

I'm currently traveling so I have limited time. Doing it in a separate module sounds perfect!

**Comment by serpro69** [comment]
Did some very simple implementation in #254 . Feel free to take a look and provide some feedback, if you like ;)

**Comment by serpro69** [comment]
Should be available in the latest 2.1.0-SNAPSHOT version once the build is complete.
