### ISSUE TITLE
Parameter 'city_name' not found in 'address' for 'lv' locale

### ISSUE THREAD

**Issue by serpro69** [serpro69/kotlin-faker#45]
Sample code:
```
FakerConfig fakerConfig = FakerConfigBuilder.create(FakerConfig.builder(), fromConsumer(builder -> {
    builder.setLocale("lv");
    builder.setRandom(new Random(42));
}));
Faker faker = new Faker(fakerConfig);
System.out.println(faker.getAddress().fullAddress());
```

This, most likely applies to other locales as well.

Thought unit tests covered this already

**Comment by leomillon** [comment]
Hi @serpro69

I just got the same issue with the `fr` locale :/

Is it possible to override the configuration while a fix is available?

Thx

**Comment by serpro69** [comment]
Hi,
No, I don't think it's possible to "override" if I understand correctly what you mean by that, but I can make a fix pretty fast for this.

**Comment by serpro69** [comment]
Hi,
No, I don't think it's possible to "override" if I understand correctly what you mean by that, but I can make a fix pretty fast for this.

**Comment by serpro69** [comment]
Took a slightly different approach to fix this than last time, since this issue is prevalent in multiple localized dictionaries, not just `lv` and `fr`.

A `1.7.1` version with the fix should be available in the maven central now.
@leomillon FYI

**Comment by leomillon** [comment]
Thanks a lot @serpro69 for your quick reaction 👍
