### ISSUE TITLE
Update to Kotlin 1.4.31 and Jackson 2.12.1

### ISSUE THREAD

**Issue by PeekAndPoke** [serpro69/kotlin-faker#61]
I recently update the dependencies in a project of mine to Kotlin 1.4.31 and Jackson >= 2.12.

This in fact leads to a NoClassDefFound Exception at the Mapper class of Faker. To be precise at this line:

```
    init {
        mapper.registerModule(KotlinModule())
    }
```
So I would highly appreciate an updated version with updated dependencies! Thanks a lot!

**Comment by serpro69** [comment]
Hi @PeekAndPoke and thanks for submitting this issue!
Have been meaning to go over the dependencies and upgrade things. I'll look at it during this weekend.

**Comment by serpro69** [comment]
Closed with https://github.com/serpro69/kotlin-faker/commit/668a98a32722cdb2ac484377021770609e7ee291

Until this gets into a stable release you can use release-candidate version with these changes from: `https://dl.bintray.com/serpro69/maven-release-candidates/` repo . (See also [downloading](https://github.com/serpro69/kotlin-faker#downloading) part of the readme for more details)

Will also add "snapshots" later on when https://github.com/serpro69/kotlin-faker/issues/60 is done.

**Comment by tarciosaraiva** [comment]
+1 on this. Just ran into this issue and is quite annoying. Any chance this will be promoted to stable soon?

**Comment by serpro69** [comment]
Hi @tarciosaraiva . 
Yes, I wanted to move the whole thing outside of jcenter first, and I haven't had time to look into it yet. But might as well just publish another release on jcenter and sync it with maven central.

**Comment by serpro69** [comment]
It's now in a stable release and should also be available in maven central.
fyi @tarciosaraiva , @PeekAndPoke
