### ISSUE TITLE
FakerConfig seed parameter

### ISSUE THREAD

**Issue by johanvergeer** [serpro69/kotlin-faker#68]
Passing in a `Random` instance is most of the time just to set a `seed`. 

Therefore it would be nice when there would be a `seed` parameter, which is used by the default `Random` instance.

**Comment by serpro69** [comment]
Does this look like what you had in mind, @johanvergeer : https://github.com/serpro69/kotlin-faker/pull/69/commits/56568b8b8ecf575d6d92714a7c7597b3ccf74f95 ?

**Comment by johanvergeer** [comment]
Yes. That looks pretty good. I did add a suggestion to the commit though, which might make it a bit simpler. :)

**Comment by serpro69** [comment]
Thanks for the suggestion. You're right, the secondary constructor there does not add any value.
I've merged this now into master and these changes have been published as snapshot and should be available shortly.
