### ISSUE TITLE
Check mock requests body

### ISSUE THREAD

**Issue by mfamador** [serpro69/kotlin-faker#84]
Hi!
I was trying to create some `POST` mocks on which I want to get different responses depending on the request body values.
I'm struggling to retrieve the request body on `JsonRouter` from the `ServerHttpRequest` request so that I can match the requests to the mock specs.
Do you have any idea how could we get the body contents here?
Thanks!

**Comment by serpro69** [comment]
Hi @mfamador ,
Are you sure you've made this issue in the correct project? What you are describing has nothing to do with kotlin-faker functionality.

**Comment by mfamador** [comment]
Oh, yeah, wrong project :D sorry about that
